---
name: Haddocks to Github Pages
on: push
branch: master
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: cabal-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project', 'candid.cabal') }}
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: 9.0
    - name: Build
      run: |
        cabal update
        cabal haddock --haddock-hyperlink-source --haddock-quickjump --haddock-html-location='https://hackage.haskell.org/package/$pkg-$version/docs'
        mv dist-newstyle/build/*/*/*/doc/html/candid gh-page
        touch gh-page/.nojekyll
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: gh-page
        SINGLE_COMMIT: true
